name: smart_device_tester
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0 # Dependencia requerida para Parte 2 Mocking de dependencias
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true